Public API sketch  -- fails with Definitions.cs(104,45): error CS0117: 'FSharpFunc<string, Unit>' does not contain a definition for 'FromConverter' [C:\Users\steve\Documents\GitHub\altcover\altcover.CSApi\altcover.csapi.core.csproj]  -- may have issues with being .netcore2.0 rather than netstandard2.0 (may need to push all of the existing AltCover.dll into an AltCover.Core.dll and have a thin Main on top of it.